import Ldse

l = Ldse.Ldse()
l.inserirInicio("A")
l.inserirInicio("B")
print("Show 1")
l.show()
print(l.getPrim())
print(l.getUlt())
#l.inserirFim("C")
l.inserirInicio("C")
print("Show 2")
l.show()
#print(l.getUlt())
l.inserirInicio("D")
print("Show 3")
l.show()
print("Tentando o fim de novo")
l.inserirFim("C")
l.show()
la=Ldse.Ldse()

print("Remover Fim")
la.inserirInicio("C")
la.inserirInicio("B")
la.inserirInicio("A")
print("Show 1")
la.show()
la.removerFim()
print("Show 2")
la.show()
